language: node_js
node_js:
  - "lts/*"
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE hotmeal;" -U postgres
  - psql -c "CREATE USER hotmealuser WITH PASSWORD '1';" -U postgres  